apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vuelos2024-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/sarasti2/reservas_argoscd # Cambia esto por tu URL de Git
    targetRevision: HEAD
    path: manifests
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true